### PR TITLE
Update to JSS 21.1.0 canary

### PR DESCRIPTION
**Pull request by ambrauer**
This PR updates the starter kit to the latest JSS 21.1.0 canary version (i.e. `npx create-sitecore-jss@canary nextjs,nextjs-sxa,nextjs-personalize`)

### CODE REVIEW

**Review by sc-dawidrutkowski — COMMENTED** [review]
Looks fine to me but I will leave the review for the UI dev.

**Review by matkovskyi — APPROVED** [review]

**Comment by matkovskyi** [comment]
Looks good!

**Review by sc-dawidrutkowski — APPROVED** [review]

**Comment by illiakovalenko** [comment]
@ambrauer I will take a look

**Review by illiakovalenko — APPROVED** [review]
Looks good to me! 👍

**Pull request merged**
