### PR TITLE
 #592757: fixed command of run jss scaffold BYOC

### PR DESCRIPTION
**Pull request by matkovskyi**

### CODE REVIEW

**Review by StanislavStativa — APPROVED** [review]

**Review by ambrauer — CHANGES_REQUESTED** [review]
@matkovskyi Hard to tell what changed, but need to keep jss package dependencies using '~' and the lock file format using version 3 (node 18 / npm 9).

**Comment by matkovskyi** [comment]
> @matkovskyi Hard to tell what changed, but need to keep jss package dependencies using '~' and the lock file format using version 3 (node 18 / npm 9).

I fixed.
I added fix for run command scaffold components

**Comment by ambrauer** [comment]
> > @matkovskyi Hard to tell what changed, but need to keep jss package dependencies using '~' and the lock file format using version 3 (node 18 / npm 9).
> 
> I fixed. I added fix for run command scaffold components

I see. The fix for "scaffold" script in package.json makes sense. Please update the title/description of the PR to reflect this.
What are the changes in `package-lock.json` required for? The format is still incorrect (downgraded from v3 -> v1), btw.

**Comment by matkovskyi** [comment]
> > > @matkovskyi Hard to tell what changed, but need to keep jss package dependencies using '~' and the lock file format using version 3 (node 18 / npm 9).
> > 
> > 
> > I fixed. I added fix for run command scaffold components
> 
> I see. The fix for "scaffold" script in package.json makes sense. Please update the title/description of the PR to reflect this. What are the changes in `package-lock.json` required for? The format is still incorrect (downgraded from v3 -> v1), btw.

Maybe need to add "engines: {node: ">=18 <19"} section into package.json file?

**Review by ambrauer — APPROVED** [review]

**Pull request merged**
